# Generated by Django 5.0.1 on 2024-01-21 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentACar', '0006_alter_review_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='production_year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
